"""empty message

Revision ID: 007f13665f58
Revises: 74f9bafc1557
Create Date: 2020-07-06 13:47:17.880152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007f13665f58'
down_revision = '74f9bafc1557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Show', ['show_id'], ['id'])
    op.add_column('Venue', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Show', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show_id')
    # ### end Alembic commands ###
