"""empty message

Revision ID: 74f9bafc1557
Revises: bbe099cc710f
Create Date: 2020-07-06 13:40:48.642115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f9bafc1557'
down_revision = 'bbe099cc710f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_show_id_fkey', 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show_id')
    op.drop_constraint('Venue_show_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_show_id_fkey', 'Venue', 'Show', ['show_id'], ['id'])
    op.add_column('Artist', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Artist_show_id_fkey', 'Artist', 'Show', ['show_id'], ['id'])
    # ### end Alembic commands ###
