"""empty message

Revision ID: bbe099cc710f
Revises: c58d16970f2f
Create Date: 2020-07-05 22:11:44.378064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbe099cc710f'
down_revision = 'c58d16970f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Show', ['show_id'], ['id'])
    op.add_column('Venue', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Show', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show_id')
    op.drop_table('Show')
    # ### end Alembic commands ###
